# Generated by Django 4.0.1 on 2022-01-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_musclegroup_exercise_musclegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscleGroup',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Bicep', 'Bicep'), ('Tricep', 'Tricep'), ('Back', 'Back'), ('Legs', 'Legs')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MuscleGroup',
        ),
    ]
