# Generated by Django 4.0.1 on 2022-01-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_exercise_musclegroup_delete_musclegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscleGroup',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Bicep', 'Bicep'), ('Tricep', 'Tricep'), ('Back', 'Back'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
            ],
        ),
    ]
