# Generated by Django 4.0.1 on 2022-01-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_exercise_musclegroup_workout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
