# Generated by Django 4.0.1 on 2022-01-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ManyToManyField(to='api.Category'),
        ),
    ]
