# Generated by Django 4.0.1 on 2022-01-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_musclegroup_remove_exercise_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercise', models.ManyToManyField(null=True, to='api.Exercise')),
            ],
        ),
    ]
