# Generated by Django 4.0.1 on 2022-01-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_equipment_exercise_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ManyToManyField(to='api.Category'),
        ),
    ]
