# Generated by Django 4.0.1 on 2022-01-09 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Chest', 'Chest'), ('Bicep', 'Bicep'), ('Tricep', 'Tricep'), ('Back', 'Back'), ('Legs', 'Legs')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscleGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.musclegroup'),
        ),
    ]
