# Generated by Django 4.0.1 on 2022-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_category_name_alter_musclegroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscleGroup',
            field=models.ManyToManyField(to='api.MuscleGroup'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.ManyToManyField(to='api.Exercise'),
        ),
    ]
