# Generated by Django 4.0.1 on 2022-01-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_exercise_musclegroup_alter_workout_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='calorie',
        ),
    ]
