# Generated by Django 4.0.1 on 2022-01-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_exercise_calorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
    ]
